# Core Settings

name: Bruno Giarrizzo

description: Bruno Giarrizzo, Freelance, Developer & DevOps
description_meta: "Bruno Giarrizzo, Papa, Freelance, Developpeur & DevOps. Parle de code, de développement personnel, d'investissement et de business."
description_long: >
  Papa, Freelance, Developpeur & DevOps. Parle de code, de développement personnel, d'investissement et de business. <br /><br />
  <a href="/about/">Contactez moi</a> pour toute question, ou <a href="https://paypal.me/bgiarrizzo" target="_blank">soutenez mon travail</a> !

keywords:
  [
    Bruno,
    Giarrizzo,
    Bruno Giarrizzo,
    Freelance,
    Développeur,
    DevOps,
    Ethical Hacker,
    Ethical,
    Hacker,
    Django,
    Python,
    Swift,
    Ansible,
    Terraform,
    Kubernetes,
    Infra as Code,
    Investissement,
    Immobilier,
    Entrepreneuriat,
    Business,
    Entreprise,
  ]

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: https://www.bruno-giarrizzo.fr

author_avatar: "images/photo-min.jpg"
# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: bruno-giarrizzo

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-178521232-1

# Misc

footer_bio: >
  <p>Bruno, DevOps, Lillois, Marié et Papa d'une petite fille.</p>
  <p>iPhone à la main, Macbook dans le sac à dos, je cherche toujours la petite bête à coder.</p>
  <p>Je partage ici : du code, du business, du développement personnel, du WTF.</p>

social_ids:
  twitter: b_giarrizzo
  instagram: bgiarrizzo
  youtube: UCSXj4YcwcmH57INCrNAR03Q
  github: bgiarrizzo
  gitlab: bgiarrizzo

email: contact@bruno-giarrizzo.fr

# -----------------------------------------
# Podcast Settings

podcast_title: "Unlock Business & Code"
podcast_subtitle: "Sous titre"
podcast_description: "J'apprends le business, l'investissement, je suis aussi freelance en IT. Je partage ici ce que j'apprendrai au cours de mon voyage."

author: Bruno Giarrizzo
author_url: "https://www.bruno-giarrizzo.fr/"

itunes_categories:
  - <itunes:category text="Business"><itunes:category text="Investing" /></itunes:category>
  - <itunes:category text="Society &amp; Culture"><itunes:category text="Documentary" /></itunes:category>
  - <itunes:category text="Technology" />

date_format: ordinal

language: fr
explicit: "no" # "yes" | "no" | clean

### License Config, you really should configure this
license: 4.0
license_url: https://creativecommons.org/licenses/by/4.0/
license_image_url: https://i.creativecommons.org/l/by/4.0/88x31.png

### Feed links, optional
podcast_links:
  itunes_url: https://itunes.apple.com/at/podcast/myname/id232323
  google_play_url: https://playmusic.app.goo.gl/...
  youtube_url: https://www.youtube.com/channel/UCSXj4YcwcmH57INCrNAR03Q
  spotify_url: https://spotify.com/

download_url: ""
episodes_per_feed_page: 100

# -----------------------------------------
# Build settings

plugins:
  - jekyll-octopod

exclude:
  - .gitignore
  #   - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

collections:
  # Blog Categories
  category:
    output: true
    permalink: /:collection/:name/
  # Resume sections exploded in markdown files
  resume:
    output: true
  # book listing in markdown files
  books:
    output: true
  # links
  links:
    output: true

defaults:
  - scope:
      path: ""
      type: category
    values:
      layout: "category"
